
[YouTube]
enabled = false
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Music]
enabled = true
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[GooglePhotos]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
