
[YouTube]
enabled = true
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"
arch = "all"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
enabled = true
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patcher-args = "-e 'Custom branding name for YouTube Music' -e 'Custom branding icon for YouTube Music' -OappIcon='Revancify Blue'"

[GooglePhotos]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"
